/* Generated by wayland-scanner 1.11.0 */

/*
 * Copyright (c) 2012 Advanced Driver Information Technology.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface ivi_share_surface_interface;

static const struct wl_interface *types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&ivi_share_surface_interface,
	NULL,
};

static const struct wl_message ivi_share_requests[] = {
	{ "get_ivi_share_surface", "nu", types + 5 },
};

WL_EXPORT const struct wl_interface ivi_share_interface = {
	"ivi_share", 1,
	1, ivi_share_requests,
	0, NULL,
};

static const struct wl_message ivi_share_surface_requests[] = {
	{ "destroy", "", types + 0 },
	{ "redirect_touch_down", "uiff", types + 0 },
	{ "redirect_touch_up", "ui", types + 0 },
	{ "redirect_touch_motion", "iff", types + 0 },
	{ "redirect_touch_frame", "", types + 0 },
	{ "redirect_touch_cancel", "", types + 0 },
};

static const struct wl_message ivi_share_surface_events[] = {
	{ "damage", "u", types + 0 },
	{ "configure", "uuuuu", types + 0 },
	{ "input_capabilities", "u", types + 0 },
	{ "share_surface_state", "u", types + 0 },
};

WL_EXPORT const struct wl_interface ivi_share_surface_interface = {
	"ivi_share_surface", 1,
	6, ivi_share_surface_requests,
	4, ivi_share_surface_events,
};

