/* Generated by wayland-scanner 1.11.0 */

/*
 * Copyright (c) 2015 Codethink Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *types[] = {
	NULL,
	NULL,
	NULL,
};

static const struct wl_message ivi_input_requests[] = {
	{ "set_input_focus", "uui", types + 0 },
	{ "set_input_acceptance", "usi", types + 0 },
};

static const struct wl_message ivi_input_events[] = {
	{ "seat_created", "su", types + 0 },
	{ "seat_capabilities", "su", types + 0 },
	{ "seat_destroyed", "s", types + 0 },
	{ "input_focus", "uui", types + 0 },
	{ "input_acceptance", "usi", types + 0 },
};

WL_EXPORT const struct wl_interface ivi_input_interface = {
	"ivi_input", 1,
	2, ivi_input_requests,
	5, ivi_input_events,
};

